### ISSUE TITLE
¿.childNodes o .children?

### ISSUE THREAD

**Issue by livchits** [undefinedschool/notes-dom#1]
Hola,

[Acá](https://github.com/undefinedschool/notes-dom#todos-los-descendientes) me parece que están invertidas las explicaciones de las propiedades `.childNodes` y `.children`.

🤔

**Comment by nhsz** [comment]
Si, es verdad, se me mezclaron. Querés armar un PR?

**Comment by livchits** [comment]
Dale, en un rato lo armo.

**Comment by nhsz** [comment]
Resuelto en https://github.com/undefinedschool/notes-dom/pull/2
